# Generated by Django 5.0 on 2024-06-28 17:03

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codificadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaCostoProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='Crate at')),
                ('fecha', models.DateField(verbose_name='Date')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='The value must be greater than 0')])),
                ('tasa', models.DecimalField(db_comment='Tasa', decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='The value must be greater than 0')], verbose_name='Tasa')),
                ('activa', models.BooleanField(default=False, verbose_name='Active')),
                ('confirmada', models.BooleanField(default=False, verbose_name='Confirmada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productoflujo_ficha', to='codificadores.productoflujo', verbose_name='Product')),
                ('um', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ficha_medida', to='codificadores.medida', verbose_name='U.M')),
            ],
            options={
                'db_table': 'cos_fichacostoproducto',
                'ordering': ['fecha', 'producto', 'confirmada', '-activa'],
            },
        ),
        migrations.CreateModel(
            name='FichaCostoProductoFilas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo')),
                ('fichacostoproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichacostoproducto_ficha', to='costo.fichacostoproducto', verbose_name='Ficha de Costo')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichacostoproducto_fila', to='codificadores.fichacostofilas')),
            ],
            options={
                'db_table': 'cos_fichacostoproductofila',
                'ordering': ['fila'],
            },
        ),
        migrations.CreateModel(
            name='FichaCostoProductoFilaDesgloseMPMat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('costo_base_norma', models.DecimalField(db_default=models.Value(0.0), decimal_places=4, max_digits=10, verbose_name='Norma Costo Base')),
                ('costo_base_precio', models.DecimalField(db_default=models.Value(0.0), decimal_places=6, max_digits=10, verbose_name='Precio Costo Base')),
                ('costo_base_importe', models.DecimalField(db_default=models.Value(0.0), decimal_places=2, max_digits=10, verbose_name='Importe Costo Base')),
                ('costo_propuesto_norma', models.DecimalField(db_default=models.Value(0.0), decimal_places=4, max_digits=10, verbose_name='Norma Costo Base')),
                ('costo_propuesto_precio', models.DecimalField(db_default=models.Value(0.0), decimal_places=6, max_digits=10, verbose_name='Precio Costo Base')),
                ('costo_propuesto_importe', models.DecimalField(db_default=models.Value(0.0), decimal_places=2, max_digits=10, verbose_name='Importe Costo Propuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filadesglose_producto', to='codificadores.productoflujo', verbose_name='Product')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desglosempmat_fila', to='costo.fichacostoproductofilas', verbose_name='Fila')),
            ],
            options={
                'db_table': 'cos_fichacostoproductofiladesglosempmat',
                'ordering': ['fila', 'producto'],
            },
        ),
        migrations.AddIndex(
            model_name='fichacostoproducto',
            index=models.Index(fields=['producto', 'activa'], name='cos_fichaco_product_9e1876_idx'),
        ),
        migrations.AddConstraint(
            model_name='fichacostoproductofilas',
            constraint=models.UniqueConstraint(fields=('fila', 'fichacostoproducto'), name='unique_fichacostoproductofila_fila_fichacostoproducto'),
        ),
        migrations.AddConstraint(
            model_name='fichacostoproductofiladesglosempmat',
            constraint=models.UniqueConstraint(fields=('fila', 'producto'), name='unique_fichacostoproductofiladesglosempmat_fila_producto'),
        ),
    ]
