# Generated by Django 5.0.7 on 2024-07-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichacostoproductofiladesglosempmat',
            name='costo_base_importe',
            field=models.DecimalField(db_default=0.0, decimal_places=2, max_digits=10, verbose_name='Importe Costo Base'),
        ),
        migrations.AlterField(
            model_name='fichacostoproductofiladesglosempmat',
            name='costo_base_norma',
            field=models.DecimalField(db_default=0.0, decimal_places=4, max_digits=10, verbose_name='Norma Costo Base'),
        ),
        migrations.AlterField(
            model_name='fichacostoproductofiladesglosempmat',
            name='costo_base_precio',
            field=models.DecimalField(db_default=0.0, decimal_places=6, max_digits=10, verbose_name='Precio Costo Base'),
        ),
        migrations.AlterField(
            model_name='fichacostoproductofiladesglosempmat',
            name='costo_propuesto_importe',
            field=models.DecimalField(db_default=0.0, decimal_places=2, max_digits=10, verbose_name='Importe Costo Propuesto'),
        ),
        migrations.AlterField(
            model_name='fichacostoproductofiladesglosempmat',
            name='costo_propuesto_norma',
            field=models.DecimalField(db_default=0.0, decimal_places=4, max_digits=10, verbose_name='Norma Costo Base'),
        ),
        migrations.AlterField(
            model_name='fichacostoproductofiladesglosempmat',
            name='costo_propuesto_precio',
            field=models.DecimalField(db_default=0.0, decimal_places=6, max_digits=10, verbose_name='Precio Costo Base'),
        ),
    ]
