# Generated by Django 5.0 on 2024-02-20 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codificadores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConexionBaseDato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('database_name', models.CharField(max_length=250, verbose_name='Database Name')),
                ('database_user', models.CharField(max_length=250, verbose_name='User Name')),
                ('password', models.CharField(max_length=250, verbose_name='Password')),
                ('host', models.CharField(max_length=250, verbose_name='Host')),
                ('port', models.CharField(max_length=100, verbose_name='Port')),
                ('idunidadcontable', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='codificadores.unidadcontable', verbose_name='UEB')),
            ],
            options={
                'db_table': 'cfg_conexionasedato',
            },
        ),
        migrations.CreateModel(
            name='ConsecutivoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField(verbose_name='Number')),
                ('idnumeraciondocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consecutivodocumento_numeracion', to='codificadores.numeraciondocumentos', verbose_name='Enumeration Type')),
                ('idueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consecutivo_ueb', to='codificadores.unidadcontable', verbose_name='UEB')),
            ],
            options={
                'db_table': 'cfg_consecutivodocumento',
            },
        ),
        migrations.CreateModel(
            name='ConsecutivoDocumentoDepartamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idconsecutivodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consecutivodocumentodpto_consecutivodocumento', to='configuracion.consecutivodocumento')),
                ('iddepartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consecutivodocumentodpto_departamento', to='codificadores.departamento', verbose_name='Department')),
            ],
            options={
                'db_table': 'cfg_consecutivodocumentodepartamento',
            },
        ),
        migrations.CreateModel(
            name='ConsecutivoDocumentoTipoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idconsecutivodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consecutivodocumentotipodoc_consecutivodocumento', to='configuracion.consecutivodocumento')),
                ('idtipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consecutivodocumentotipodoc_tipodocumento', to='codificadores.tipodocumento')),
            ],
            options={
                'db_table': 'cfg_consecutivodocumentotipodocumento',
            },
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserUeb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ueb_user', to='codificadores.unidadcontable')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_ueb', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cfg_userueb',
            },
        ),
    ]
