# Generated by Django 5.0 on 2024-01-19 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codificadores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('idnumeraciondocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consecutivodocumento_numeracion', to='codificadores.numeraciondocumentos')),
            ],
            options={
                'db_table': 'cfg_consecutivodocumento',
            },
        ),
        migrations.CreateModel(
            name='ConsecutivoDocumentoDepartamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idconsecutivodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consecutivodocumentodpto_consecutivodocumento', to='configuracion.consecutivodocumento')),
                ('iddepartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consecutivodocumentodpto_departamento', to='codificadores.departamento')),
            ],
            options={
                'db_table': 'cfg_consecutivodocumentodepartamento',
            },
        ),
        migrations.CreateModel(
            name='ConsecutivoDocumentoTipoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idconsecutivodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consecutivodocumentotipodoc_consecutivodocumento', to='configuracion.consecutivodocumento')),
                ('idtipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consecutivodocumentotipodoc_tipodocumento', to='codificadores.tipodocumento')),
            ],
            options={
                'db_table': 'cfg_consecutivodocumentotipodocumento',
            },
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ueb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idunidadcontable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'cfg_ueb',
            },
        ),
        migrations.AddField(
            model_name='consecutivodocumento',
            name='idueb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consecutivo_ueb', to='configuracion.ueb'),
        ),
        migrations.CreateModel(
            name='UserUeb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ueb_user', to='configuracion.ueb')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_ueb', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cfg_userueb',
            },
        ),
        migrations.CreateModel(
            name='ConexionBaseDato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('database_name', models.CharField(max_length=250)),
                ('database_user', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('host', models.CharField(max_length=250)),
                ('port', models.CharField(max_length=100)),
                ('idueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.ueb')),
            ],
            options={
                'db_table': 'cfg_conexionasedato',
                'unique_together': {('database_name', 'idueb')},
            },
        ),
    ]
