# Generated by Django 5.0 on 2024-02-20 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0003_alter_departamento_departamentoproducto_and_more'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conexionbasedato',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='conexionbasedato',
            name='idueb',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='codificadores.unidadcontable', verbose_name='UEB'),
        ),
    ]
