# Generated by Django 5.0 on 2024-02-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexionbasedato',
            name='sistema',
            field=models.CharField(default='VersatSarasola', max_length=50, verbose_name='System'),
        ),
    ]
