# Generated by Django 5.0 on 2024-02-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0002_alter_centrocosto_options_alter_cuenta_options_and_more'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conexionbasedato',
            options={'ordering': ['idunidadcontable__codigo', 'sistema'], 'verbose_name': 'Database conexion', 'verbose_name_plural': 'Conexions of data bases'},
        ),
        migrations.AddField(
            model_name='conexionbasedato',
            name='sistema',
            field=models.CharField(default='VersatSarasola', max_length=50, verbose_name='System'),
        ),
        migrations.AddIndex(
            model_name='conexionbasedato',
            index=models.Index(fields=['idunidadcontable', 'sistema'], name='cfg_conexio_idunida_ace0f6_idx'),
        ),
    ]
