# Generated by Django 5.0 on 2024-02-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_alter_conexionbasedato_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conexionbasedato',
            old_name='idueb',
            new_name='idunidadcontable',
        ),
    ]
