# Generated by Django 5.0 on 2024-02-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0003_alter_centrocosto_options_alter_cuenta_options_and_more'),
        ('configuracion', '0002_conexionbasedato_sistema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conexionbasedato',
            options={'ordering': ['idunidadcontable__codigo', 'sistema'], 'verbose_name': 'Database conexion', 'verbose_name_plural': 'Conexions of data bases'},
        ),
        migrations.AddIndex(
            model_name='conexionbasedato',
            index=models.Index(fields=['idunidadcontable', 'sistema'], name='cfg_conexio_idunida_ace0f6_idx'),
        ),
    ]
