# Generated by Django 5.0 on 2023-12-28 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codificadores', '0001_initial'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('fecha_creado', models.DateField()),
                ('numerocontrol', models.CharField(max_length=50)),
                ('numeroconsecutivo', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('rechazado', models.BooleanField(default=False)),
                ('reproceso', models.BooleanField(default=False)),
                ('editar_nc', models.BooleanField(default=False)),
                ('comprob', models.CharField(blank=True, max_length=150, null=True)),
                ('iddepartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documento_departamento', to='codificadores.departamento')),
                ('idtipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documento_tipodocumento', to='codificadores.tipodocumento')),
                ('idueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documento_tipodocumento', to='configuracion.ueb')),
            ],
            options={
                'db_table': 'fp_documento',
                'ordering': ['idueb', 'iddepartamento', 'idtipodocumento', '-numeroconsecutivo'],
                'unique_together': {('numeroconsecutivo', 'idtipodocumento', 'iddepartamento', 'idueb')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoAjuste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iddocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentoajuste_documento', to='flujo.documento')),
                ('idmotivoajuste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentoajuste_motivo', to='codificadores.motivoajuste')),
            ],
            options={
                'db_table': 'fp_documentoajuste',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=6, default=0.0, max_digits=18)),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('existencia', models.DecimalField(decimal_places=6, default=0.0, max_digits=18)),
                ('iddocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalle_documento', to='flujo.documento')),
                ('idestado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalle_productoestado', to='codificadores.estadoproducto')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalle_producto', to='codificadores.productoflujo')),
            ],
            options={
                'db_table': 'fp_documentodetalle',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleEstado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('existencia', models.DecimalField(decimal_places=6, default=0.0, max_digits=18)),
                ('iddocumentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalleestado_detalle', to='flujo.documentodetalle')),
                ('idestado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalleestado_estado', to='codificadores.estadoproducto')),
            ],
            options={
                'db_table': 'fp_documentodetalleestado',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('existencia', models.DecimalField(decimal_places=6, default=0.0, max_digits=18)),
                ('iddocumentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalleproducto_detalle', to='flujo.documentodetalle')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalleproducto_producto', to='codificadores.productoflujo')),
            ],
            options={
                'db_table': 'fp_documentodetalleproducto',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleVenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('iddocumentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalleventa_detalle', to='flujo.documentodetalle')),
            ],
            options={
                'db_table': 'fp_documentodetalleventa',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDevolucion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iddocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodevolucion_documento', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentodevolucion',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDevolucionRecibida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iddocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodevolucionrecibida_documento', to='flujo.documento')),
                ('iddocumentoorigen', models.ForeignKey(db_comment='Documento que originó la devolucion hacia el departamento', on_delete=django.db.models.deletion.PROTECT, related_name='documentodevolucionrecibida_documentoorigen', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentodevolucionrecibida',
            },
        ),
        migrations.CreateModel(
            name='DocumentoOrigenVersat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iddocumentoversat', models.IntegerField()),
                ('iddocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentoorigenversat_documento', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentoorigenversat',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfDepartamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iddepartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfdepartamento_departamento', to='codificadores.departamento')),
                ('iddocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfdepartamento_documento', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentotransfdepartamento',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfDepartamentoRecibida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iddocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfdepartamentorecibida_documento', to='flujo.documento')),
                ('iddocumentoorigen', models.ForeignKey(db_comment='Documento que originó la transferencia hacia el departamento', on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfdepartamentorecibida_documentoorigen', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentotransfdesdedepartamento',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfExterna',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iddocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfext_documento', to='flujo.documento')),
                ('idunidadcontable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfext_unidadcontable', to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'fp_documentotransfexterna',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfExternaDptoDestino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iddocumentotransfext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentotransfextdptodest_documento', to='flujo.documento')),
                ('iddptodestino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfextdptodest_dptodest', to='codificadores.departamento')),
            ],
            options={
                'db_table': 'fp_documentotransfexternadptodestino',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfExternaRecibida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iddocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfextrecibida_documento', to='flujo.documento')),
                ('idunidadcontable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfextrecibida_unidadcontable', to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'fp_documentotransfexternarecibida',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfExternaRecibidaDocOrigen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iddocumentoorigen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfextrecibida_documentoorigen', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentotransfexternarecibidadocorigen',
            },
        ),
        migrations.CreateModel(
            name='DocumentoVersatRechazado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iddocumentoversat', models.IntegerField()),
                ('idueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentoversatrechazado_ueb', to='configuracion.ueb')),
            ],
            options={
                'db_table': 'fp_documentoversatrechazado',
            },
        ),
        migrations.CreateModel(
            name='FechaCierreMes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('idueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechacierremes_ueb', to='configuracion.ueb')),
            ],
            options={
                'db_table': 'fp_fechacierremes',
                'unique_together': {('fecha', 'idueb')},
            },
        ),
        migrations.CreateModel(
            name='FechaPeriodo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('iddepartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechaperiodo_departamento', to='codificadores.departamento')),
                ('idueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechaperiodo_ueb', to='configuracion.ueb')),
            ],
            options={
                'db_table': 'fp_fechaperiodo',
                'unique_together': {('fecha', 'iddepartamento', 'idueb')},
            },
        ),
    ]
