# Generated by Django 5.0 on 2024-06-28 17:03

import codificadores.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django_choices_field.fields
import flujo.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codificadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Date')),
                ('fecha_creacion', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='Create at')),
                ('numerocontrol', models.CharField(max_length=50, verbose_name='Control Number')),
                ('numeroconsecutivo', models.IntegerField(verbose_name='Consecutive Number')),
                ('suma_importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('estado', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Edición'), (2, 'Confirmado'), (3, 'Rechazado'), (4, 'Cancelado')], choices_enum=flujo.models.EstadosDocumentos, db_comment='Estado del documento 1:Edición, 2:Confirmado, 3:Rechazado', verbose_name='Status')),
                ('reproceso', models.BooleanField(default=False, verbose_name='Reprocessing')),
                ('editar_nc', models.BooleanField(default=False)),
                ('comprob', models.CharField(blank=True, max_length=150, null=True)),
                ('anno', models.IntegerField(default=0)),
                ('mes', models.IntegerField(default=0)),
                ('confconsec', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Por departamento'), (2, 'Unico en el sistema')], choices_enum=codificadores.models.ConfigNumero, db_comment='Para guardar el tipo de conf para el consecutivo y poder establecer la constarint', default=1)),
                ('confcontrol', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Por departamento'), (2, 'Unico en el sistema')], choices_enum=codificadores.models.ConfigNumero, db_comment='Para guardar el tipo de conf para el numero de control y poder establecer la constarint', default=1)),
                ('error', models.BooleanField(default=False, verbose_name='Error')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documento_departamento', to='codificadores.departamento')),
                ('tipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documento_tipodocumento', to='codificadores.tipodocumento')),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documento_ueb', to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'fp_documento',
                'ordering': ['ueb', 'departamento', '-numeroconsecutivo', 'tipodocumento'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAjuste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentoajuste_documento', to='flujo.documento')),
                ('motivoajuste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentoajuste_motivo', to='codificadores.motivoajuste', verbose_name='Adjustment Reason')),
            ],
            options={
                'db_table': 'fp_documentoajuste',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, validators=[django.core.validators.MinValueValidator(0.0001, message='El valor debe ser >= 0')], verbose_name='Quantity')),
                ('precio', models.DecimalField(decimal_places=7, default=0.0, max_digits=18, validators=[django.core.validators.MinValueValidator(1e-07, message='El valor debe ser >= 0')], verbose_name='Price')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('existencia', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Existence')),
                ('estado', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Bueno'), (2, 'Deficiente'), (3, 'Rechazo')], choices_enum=codificadores.models.EstadoProducto, verbose_name='Status')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentodetalle_documento', to='flujo.documento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalle_producto', to='codificadores.productoflujo', verbose_name='Product')),
            ],
            options={
                'db_table': 'fp_documentodetalle',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleEstado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('existencia', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Existence')),
                ('estado', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Bueno'), (2, 'Deficiente'), (3, 'Rechazo')], choices_enum=codificadores.models.EstadoProducto, verbose_name='Status')),
                ('documentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalleestado_detalle', to='flujo.documentodetalle')),
            ],
            options={
                'db_table': 'fp_documentodetalleestado',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('existencia', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Existence')),
                ('documentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalleproducto_detalle', to='flujo.documentodetalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalleproducto_producto', to='codificadores.productoflujo', verbose_name='Product')),
            ],
            options={
                'db_table': 'fp_documentodetalleproducto',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleTransfDptoControlTecnico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Quantity')),
                ('precio', models.DecimalField(decimal_places=7, default=0.0, max_digits=18, verbose_name='Price')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('existencia', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Existence')),
                ('buenos', models.IntegerField(default=0, verbose_name='Good')),
                ('defectuoso_cc', models.IntegerField(default=0, verbose_name='Defective CC')),
                ('defectuoso_cien', models.IntegerField(default=0, verbose_name='Defective 100%')),
                ('sensorial', models.IntegerField(default=0, verbose_name='Sensory Test')),
                ('rotos', models.IntegerField(default=0, verbose_name='Broken')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentodetalletransfdptocontroltecnico_documento', to='flujo.documento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalletransfdptocontroltecnico_producto', to='codificadores.productoflujo', verbose_name='Product')),
            ],
            options={
                'db_table': 'fp_documentodetalletransfdptocontroltecnico',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleVenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('documentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalleventa_detalle', to='flujo.documentodetalle')),
            ],
            options={
                'db_table': 'fp_documentodetalleventa',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDevolucion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodevolucion_documento', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentodevolucion',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDevolucionRecibida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodevolucionrecibida_documento', to='flujo.documento')),
                ('documentoorigen', models.ForeignKey(db_comment='Documento que originó la devolucion hacia el departamento', on_delete=django.db.models.deletion.PROTECT, related_name='documentodevolucionrecibida_documentoorigen', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentodevolucionrecibida',
            },
        ),
        migrations.CreateModel(
            name='DocumentoOrigenVersat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documentoversat', models.IntegerField()),
                ('fecha_documentoversat', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='Fecha versat at')),
                ('origen_versat', models.CharField(max_length=40)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentoorigenversat_documento', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentoorigenversat',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfDepartamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfdepartamento_departamento', to='codificadores.departamento', verbose_name='Department')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentotransfdepartamento_documento', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentotransfdepartamento',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfDepartamentoRecibida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfdepartamentorecibida_documento', to='flujo.documento')),
                ('documentoorigen', models.ForeignKey(db_comment='Documento que originó la transferencia hacia el departamento', on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfdepartamentorecibida_documentoorigen', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentotransfdesdedepartamento',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfExterna',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfext_documento', to='flujo.documento')),
                ('unidadcontable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfext_unidadcontable', to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'fp_documentotransfexterna',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfExternaDptoDestino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documentotransfext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentotransfextdptodest_documento', to='flujo.documento')),
                ('dptodestino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfextdptodest_dptodest', to='codificadores.departamento')),
            ],
            options={
                'db_table': 'fp_documentotransfexternadptodestino',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfExternaRecibida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfextrecibida_documento', to='flujo.documento')),
                ('unidadcontable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfextrecibida_unidadcontable', to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'fp_documentotransfexternarecibida',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfExternaRecibidaDocOrigen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documentoorigen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfextrecibida_documentoorigen', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentotransfexternarecibidadocorigen',
            },
        ),
        migrations.CreateModel(
            name='DocumentoVersatRechazado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documentoversat', models.IntegerField()),
                ('fecha_documentoversat', models.DateField()),
                ('fecha_rechazo', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentoversatrechazado_ueb', to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'fp_documentoversatrechazado',
            },
        ),
        migrations.CreateModel(
            name='ExistenciaDpto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Bueno'), (2, 'Deficiente'), (3, 'Rechazo')], choices_enum=codificadores.models.EstadoProducto, verbose_name='Status')),
                ('cantidad_inicial', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Cantidad Inicial')),
                ('cantidad_entrada', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Entradas')),
                ('cantidad_salida', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Salidas')),
                ('cantidad_final', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Cantidad Final')),
                ('precio', models.DecimalField(decimal_places=7, default=0.0, max_digits=18, verbose_name='Price')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias_departamento', to='codificadores.departamento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias_producto', to='codificadores.productoflujo', verbose_name='Product')),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias_ueb', to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'fp_existenciadpto',
            },
        ),
        migrations.CreateModel(
            name='FechaCierreMes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Date')),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechacierremes_ueb', to='codificadores.unidadcontable', verbose_name='UEB')),
            ],
            options={
                'db_table': 'fp_fechacierremes',
            },
        ),
        migrations.CreateModel(
            name='FechaPeriodo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Date')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechaperiodo_departamento', to='codificadores.departamento', verbose_name='Department')),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechaperiodo_ueb', to='codificadores.unidadcontable', verbose_name='UEB')),
            ],
            options={
                'db_table': 'fp_fechaperiodo',
            },
        ),
        migrations.CreateModel(
            name='NumerosDocumentos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consecutivo', models.IntegerField(default=0, verbose_name='Consecutive Number')),
                ('control', models.IntegerField(default=0, verbose_name='Consecutive Number')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numerodoc_departamento', to='codificadores.departamento', verbose_name='Department')),
                ('tipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numerodoc_tipodocumento', to='codificadores.tipodocumento')),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numerodoc_ueb', to='codificadores.unidadcontable', verbose_name='UEB')),
            ],
            options={
                'db_table': 'fp_numerosdocumentos',
            },
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(condition=models.Q(('confconsec', 1)), fields=('numeroconsecutivo', 'departamento', 'mes', 'anno', 'ueb'), name='unique_numeroconsecutivo_departamento_tipodocumento'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(condition=models.Q(('confconsec', 2)), fields=('numeroconsecutivo', 'mes', 'anno', 'ueb'), name='unique_numeroconsecutivo_ueb'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(condition=models.Q(('confcontrol', 1)), fields=('numerocontrol', 'departamento', 'anno', 'ueb'), name='unique_numerocontrol_departamento'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(condition=models.Q(('confcontrol', 2)), fields=('numerocontrol', 'anno', 'ueb'), name='unique_numerocontrol_ueb'),
        ),
        migrations.AddConstraint(
            model_name='documentodetalle',
            constraint=models.UniqueConstraint(fields=('documento', 'estado', 'producto'), name='unique_documentodetalle_documento_estado_producto'),
        ),
        migrations.AddIndex(
            model_name='existenciadpto',
            index=models.Index(fields=['producto', 'estado', 'departamento', 'ueb'], name='fp_existenc_product_d9d8fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='existenciadpto',
            constraint=models.UniqueConstraint(fields=('producto', 'estado', 'departamento', 'ueb'), name='unique_existencias_producto_estado_departamento_ueb'),
        ),
        migrations.AddConstraint(
            model_name='fechacierremes',
            constraint=models.UniqueConstraint(fields=('fecha', 'ueb'), name='unique_fechacierremes_fecha_ueb'),
        ),
        migrations.AddConstraint(
            model_name='fechaperiodo',
            constraint=models.UniqueConstraint(fields=('fecha', 'departamento', 'ueb'), name='unique_fechaperiodo_fecha_departamento_ueb'),
        ),
        migrations.AddIndex(
            model_name='numerosdocumentos',
            index=models.Index(fields=['tipodocumento', 'departamento', 'ueb'], name='fp_numerosd_tipodoc_ba11b9_idx'),
        ),
        migrations.AddIndex(
            model_name='numerosdocumentos',
            index=models.Index(fields=['tipodocumento', 'ueb'], name='fp_numerosd_tipodoc_abea0b_idx'),
        ),
        migrations.AddIndex(
            model_name='numerosdocumentos',
            index=models.Index(fields=['departamento', 'ueb'], name='fp_numerosd_departa_23d53e_idx'),
        ),
        migrations.AddIndex(
            model_name='numerosdocumentos',
            index=models.Index(fields=['ueb'], name='fp_numerosd_ueb_id_c5b490_idx'),
        ),
        migrations.AddConstraint(
            model_name='numerosdocumentos',
            constraint=models.UniqueConstraint(fields=('tipodocumento', 'departamento', 'ueb'), name='unique_numerosdocumentos_tipodocumento_departamento_ueb'),
        ),
    ]
