# Generated by Django 5.0 on 2024-06-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='existenciadpto',
            name='precio',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=18, verbose_name='Price'),
        ),
    ]
