# Generated by Django 5.0 on 2024-05-18 18:42

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoorigenversat',
            name='fecha_documentoversat',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='Fecha versat'),
        ),
    ]
