# Generated by Django 5.0 on 2024-06-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='error',
            field=models.BooleanField(default=False, verbose_name='Error'),
        ),
    ]
