# Generated by Django 5.0 on 2024-05-21 13:28

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0002_documentoorigenversat_fecha_documentoversat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentoversatrechazado',
            old_name='fecha_doc_versat',
            new_name='fecha_documentoversat',
        ),
        migrations.AlterField(
            model_name='documentoorigenversat',
            name='fecha_documentoversat',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='Fecha versat at'),
        ),
    ]
