# Generated by Django 5.0 on 2024-06-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0002_cargar_datos'),
        ('flujo', '0002_remove_numerosdocumentos_unique_numerosdocumentos_tipodocumento_departamento_ueb_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='numerosdocumentos',
            constraint=models.UniqueConstraint(fields=('tiponumero', 'departamento', 'ueb'), name='unique_numerosdocumentos_tiponumero_departamento_ueb'),
        ),
    ]
