# Generated by Django 5.0 on 2024-06-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0003_numerosdocumentos_unique_numerosdocumentos_tiponumero_departamento_ueb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numerosdocumentos',
            options={'ordering': ['ueb', 'tiponumero', 'departamento']},
        ),
    ]
