# Generated by Django 5.0 on 2024-06-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0004_alter_numerosdocumentos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerosdocumentos',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='Número'),
        ),
    ]
