# Generated by Django 5.0 on 2024-06-30 13:22

import codificadores.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0006_numdocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='numdocumento',
            name='tiponumero',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Número Consecutivo'), (2, 'Número de Control')], choices_enum=codificadores.models.TipoNumeroDoc, default=1, verbose_name='Tipo número'),
        ),
    ]
