# Generated by Django 5.0 on 2024-06-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0002_cargar_datos'),
        ('flujo', '0007_numdocumento_tiponumero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numdocumento',
            options={'ordering': ['ueb', 'tiponumero', 'departamento']},
        ),
        migrations.AddConstraint(
            model_name='numdocumento',
            constraint=models.UniqueConstraint(fields=('tiponumero', 'departamento', 'ueb'), name='unique_numdocumentos_tiponumero_departamento_ueb'),
        ),
    ]
