# Generated by Django 5.0 on 2024-06-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0008_alter_numdocumento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numdocumento',
            options={},
        ),
    ]
