# Generated by Django 5.0 on 2024-06-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0009_alter_numdocumento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numerosdocumentos',
            options={},
        ),
    ]
