# Generated by Django 5.0 on 2024-06-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0002_cargar_datos'),
        ('flujo', '0010_alter_numerosdocumentos_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='numdocumento',
            index=models.Index(fields=['departamento', 'ueb'], name='fp_numdocum_departa_bb80c9_idx'),
        ),
        migrations.AddIndex(
            model_name='numdocumento',
            index=models.Index(fields=['ueb'], name='fp_numdocum_ueb_id_3a612b_idx'),
        ),
    ]
