# Generated by Django 5.0 on 2024-06-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0011_numdocumento_fp_numdocum_departa_bb80c9_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumerosDocumentos',
        ),
    ]
