# Generated by Django 5.0 on 2024-06-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0013_rename_numdocumento_numerodocumentos'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='numerodocumentos',
            new_name='fp_numerodo_departa_6f3c32_idx',
            old_name='fp_numdocum_departa_bb80c9_idx',
        ),
        migrations.RenameIndex(
            model_name='numerodocumentos',
            new_name='fp_numerodo_ueb_id_be9977_idx',
            old_name='fp_numdocum_ueb_id_3a612b_idx',
        ),
        migrations.AlterModelTable(
            name='numerodocumentos',
            table='fp_numerodocumentos',
        ),
    ]
