# Generated by Django 5.0 on 2024-07-10 10:37

import codificadores.models
import django.db.models.deletion
import django_choices_field.fields
import flujo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0014_rename_fp_numdocum_departa_bb80c9_idx_fp_numerodo_departa_6f3c32_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Edición'), (2, 'Confirmado'), (3, 'Rechazado'), (4, 'Cancelado')], choices_enum=flujo.models.EstadosDocumentos, db_comment='Estado del documento 1:Edición, 2:Confirmado, 3:Rechazado', default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='documentodetalle',
            name='estado',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Bueno'), (2, 'Deficiente'), (3, 'Rechazo')], choices_enum=codificadores.models.EstadoProducto, default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='documentoorigenversat',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentoorigenversat_documento', to='flujo.documento'),
        ),
    ]
