# Generated by Django 5.0 on 2024-07-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0015_alter_documento_estado_alter_documentodetalle_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoorigenversat',
            name='documento_origen',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
