# Generated by Django 5.0 on 2024-07-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0016_documentoorigenversat_documento_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoorigenversat',
            name='origen_versat',
        ),
        migrations.AddField(
            model_name='documentoversatrechazado',
            name='documento_origen',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
