# Generated by Django 5.0 on 2024-07-12 13:42

import codificadores.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0017_remove_documentoorigenversat_origen_versat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentodetalle',
            name='estado',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Bueno'), (2, 'Deficiente'), (3, 'Rechazo')], choices_enum=codificadores.models.EstadoProducto, verbose_name='Status'),
        ),
    ]
