# Generated by Django 5.0.7 on 2024-07-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0018_alter_documentodetalle_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentodetalle',
            name='error',
            field=models.BooleanField(default=False, verbose_name='Error'),
        ),
    ]
