# Generated by Django 5.0.7 on 2024-07-19 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0005_remove_configuracionesgen_valor_and_more'),
        ('flujo', '0019_documentodetalle_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotransfexterna',
            name='departamento_destino',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfext_departamento_destino', to='codificadores.departamento'),
        ),
        migrations.AddField(
            model_name='documentotransfexternarecibidadocorigen',
            name='documento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='documentotransfextrecibidadocorigen_documento', to='flujo.documento'),
        ),
        migrations.AlterField(
            model_name='documentotransfexterna',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentotransfext_documento', to='flujo.documento'),
        ),
        migrations.AlterField(
            model_name='documentotransfexternarecibidadocorigen',
            name='documentoorigen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfextrecibida_documentoorigen', to='flujo.documento'),
        ),
        migrations.DeleteModel(
            name='DocumentoTransfExternaDptoDestino',
        ),
    ]
