# Generated by Django 5.0.7 on 2024-07-20 23:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0005_remove_configuracionesgen_valor_and_more'),
        ('flujo', '0020_documentotransfexterna_departamento_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentotransfexterna',
            name='departamento_destino',
        ),
        migrations.CreateModel(
            name='DocumentoTransfExternaDptoDestino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departamento_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfext_departamento_destino', to='codificadores.departamento')),
                ('documentotransfext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentotransfextdptodest_documento', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentotransfexternadptodestino',
            },
        ),
    ]
