# Generated by Django 5.0.7 on 2024-07-21 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0021_remove_documentotransfexterna_departamento_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentotransfexternarecibida',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentotransfextrecibida_documento', to='flujo.documento'),
        ),
    ]
