# Generated by Django 5.0.7 on 2024-07-24 09:25

import codificadores.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0023_documentodetalleproducto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentodetalleproducto',
            name='estado',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Bueno'), (2, 'Deficiente'), (3, 'Rechazo')], choices_enum=codificadores.models.EstadoProducto, default=1, verbose_name='Status'),
        ),
    ]
