# Generated by Django 5.0.7 on 2024-07-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0024_documentodetalleproducto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentodetalleproducto',
            name='precio',
        ),
    ]
