# Generated by Django 5.0.7 on 2024-07-24 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0025_remove_documentodetalleproducto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentodetalleproducto',
            name='documentodetalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentodetalleproducto_detalle', to='flujo.documentodetalle'),
        ),
    ]
