# Generated by Django 5.0.7 on 2024-07-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0027_documentodetalleproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentodetalleestado',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='documentodetalleestado',
            name='precio',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=18, verbose_name='Price'),
        ),
    ]
