# Generated by Django 5.0.7 on 2024-07-28 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0028_documentodetalleestado_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentodetalleestado',
            name='documentodetalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentodetalleestado_detalle', to='flujo.documentodetalle'),
        ),
    ]
