# Generated by Django 5.0.7 on 2024-07-28 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0005_remove_configuracionesgen_valor_and_more'),
        ('flujo', '0029_alter_documentodetalleestado_documentodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentodetalleestado',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalleproducto_estado', to='codificadores.productoflujo', verbose_name='Product'),
        ),
    ]
