# Generated by Django 5.0.7 on 2024-09-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0005_remove_configuracionesgen_valor_and_more'),
        ('flujo', '0030_documentodetalleestado_producto'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['ueb', 'departamento', 'fecha', 'estado'], name='fp_document_ueb_id_f0de69_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['fecha', 'numeroconsecutivo'], name='fp_document_fecha_43c607_idx'),
        ),
        migrations.AddIndex(
            model_name='documentodetalle',
            index=models.Index(fields=['documento'], name='fp_document_documen_8a66cb_idx'),
        ),
        migrations.AddIndex(
            model_name='documentodetalle',
            index=models.Index(fields=['producto'], name='fp_document_product_51ae72_idx'),
        ),
    ]
