# Generated by Django 5.0 on 2024-01-28 00:06

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVitola',
            fields=[
                ('id', models.AutoField(choices=[(5, 'IX'), (6, 'ND'), (7, 'V'), (8, 'VI'), (9, 'VII'), (10, 'VIII')], editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
                ('orden', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'cla_categoriavitola',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=25, unique=True)),
                ('clavenivel', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cla_centrocosto',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ClaseMateriaPrima',
            fields=[
                ('id', models.AutoField(choices=[(1, 'Capote'), (2, 'F1'), (3, 'F2'), (4, 'F3'), (5, 'Capa Clasificada'), (6, 'Capa sin Clasificar'), (7, 'F4')], editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80, unique=True)),
                ('capote_fortaleza', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'cla_clasemateriaprima',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id', models.AutoField(choices=[(1, 'Bueno'), (2, 'Deficiente'), (3, 'Rechazo')], editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'cla_estadoproducto',
            },
        ),
        migrations.CreateModel(
            name='FormatoCuentaProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('separador', models.CharField(max_length=1)),
                ('posicion', models.IntegerField()),
                ('longitud', models.IntegerField()),
                ('enuso', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaSalida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'cla_marcasalida',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=6, unique=True)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'cla_medida',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='MotivoAjuste',
            fields=[
                ('id', models.AutoField(choices=[(1, 'Merma'), (2, 'Rotura'), (3, 'Promoción'), (4, 'SubProductos')], editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=128, unique=True)),
                ('aumento', models.BooleanField(db_comment='Ajuste de aumento True en otro caso False', default=False)),
            ],
            options={
                'db_table': 'cla_motivoajuste',
                'ordering': ['aumento', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='NumeracionDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiponumeracion', models.CharField(choices=[(1, 'Número Consecutivo'), (2, 'Número de Control')], max_length=150, unique=True)),
                ('sistema', models.BooleanField(db_comment='Si es controlado por el sistema', default=False)),
                ('departamento', models.BooleanField(db_comment='Si el número es por departamento', default=False)),
                ('tipo_documento', models.BooleanField(db_comment='Si el número es por tipo de documento', default=False)),
                ('prefijo', models.CharField(blank=True, db_comment='Si el número de documento va a contener un prefijo', max_length=3, null=True)),
            ],
            options={
                'db_table': 'cla_numeraciondocumentos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(choices=[(1, 'Entrada Desde Versat'), (2, 'Salida Hacia Versat'), (3, 'Transferencia Hacia Departamento'), (4, 'Transferencia Desde Departamento'), (5, 'Ajuste de Aumento'), (6, 'Ajuste de Disminución'), (7, 'Recepción de Producción de Reproceso'), (8, 'Recepción de Producción'), (9, 'Devolución'), (10, 'Sobrante Sujeto a Investigación'), (12, 'Carga Inicial'), (13, 'Devolución Recibida'), (14, 'Cambio de Estado'), (15, 'Transferencia Externa'), (16, 'Recibir Transferencia Externa'), (17, 'Venta a Trabajadores'), (18, 'Reporte de SubProductos'), (19, 'Cambio de Producto')], editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=128, unique=True)),
                ('operacion', models.CharField(db_comment='Operación de Entrada (E) o Salida (S)', max_length=1)),
            ],
            options={
                'db_table': 'cla_tipodocumento',
                'ordering': ['operacion', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(choices=[(1, 'Pesada'), (2, 'Materia Prima'), (3, 'Habilitación'), (4, 'Línea de Salida'), (5, 'Vitola'), (6, 'Subproducto'), (7, 'Línea sin Terminar')], editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'cla_tipoproducto',
            },
        ),
        migrations.CreateModel(
            name='TipoVitola',
            fields=[
                ('id', models.AutoField(choices=[(1, 'Picadura'), (2, 'Hoja')], editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'cla_tipovitola',
            },
        ),
        migrations.CreateModel(
            name='UnidadContable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('is_empresa', models.BooleanField(default=False)),
                ('is_comercializadora', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cla_unidadcontable',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('long_niv', models.IntegerField()),
                ('posicion', models.IntegerField()),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('clavenivel', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('activa', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='codificadores.cuenta')),
            ],
            options={
                'db_table': 'cla_cuenta',
                'ordering': ['clave', 'posicion'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=125, unique=True)),
                ('descripcion', models.CharField(max_length=125, unique=True)),
                ('inicializado', models.BooleanField(default=False)),
                ('idcentrocosto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamento_centrocosto', to='codificadores.centrocosto')),
                ('idunidadcontable', models.ManyToManyField(related_name='departamento_unidadcontable', to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'cla_departamento',
            },
        ),
        migrations.CreateModel(
            name='NormaConsumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(choices=[(1, 'Pesada'), (2, 'Materia Prima'), (4, 'Línea de Salida'), (5, 'Vitola'), (7, 'Habilitados')], editable=False)),
                ('cantidad', models.DecimalField(decimal_places=6, default=0.0, max_digits=18)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('fecha', models.DateField()),
                ('idmedida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normaconsumo_medida', to='codificadores.medida')),
            ],
            options={
                'db_table': 'cla_normaconsumo',
                'ordering': ['tipo', 'idproducto__descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ProductoFlujo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=125, unique=True)),
                ('descripcion', models.CharField(max_length=125, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('idmedida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productoflujo_medida', to='codificadores.medida')),
                ('idtipoproducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productoflujo_tipo', to='codificadores.tipoproducto')),
            ],
            options={
                'db_table': 'cla_productoflujo',
                'ordering': ['idtipoproducto', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='NormaconsumoDetalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('norma_ramal', models.DecimalField(decimal_places=6, default=0.0, max_digits=18)),
                ('norma_empresarial', models.DecimalField(decimal_places=6, default=0.0, max_digits=18)),
                ('operativo', models.BooleanField(db_comment='Si el producto es operativo o no', default=False)),
                ('idmedida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normaconsumodetalle_medida', to='codificadores.medida')),
                ('idnormaconsumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normaconsumodetalle_normaconsumo', to='codificadores.normaconsumo')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normaconsumodetalle_producto', to='codificadores.productoflujo')),
            ],
            options={
                'db_table': 'cla_normaconsumodetalle',
            },
        ),
        migrations.AddField(
            model_name='normaconsumo',
            name='idproducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normaconsumo_producto', to='codificadores.productoflujo'),
        ),
        migrations.CreateModel(
            name='LineaSalida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('envase', models.IntegerField(default=0)),
                ('norma_embalaje', models.IntegerField(default=0)),
                ('vol_cajam3', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('peso_bruto', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('peso_neto', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('peso_legal', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('idmarcasalida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineasalida_marcasalida', to='codificadores.marcasalida')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineasalida_producto', to='codificadores.productoflujo')),
                ('idvitola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineasalida_vitola', to='codificadores.productoflujo')),
            ],
            options={
                'db_table': 'cla_lineasalida',
            },
        ),
        migrations.CreateModel(
            name='ProductoFlujoClase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idclasemateriaprima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productoflujoclase_clasemateriaprima', to='codificadores.clasemateriaprima')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoflujoclase_producto', to='codificadores.productoflujo')),
            ],
            options={
                'db_table': 'cla_productoflujoclase',
            },
        ),
        migrations.CreateModel(
            name='ProductoFlujoCuenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idcuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productoflujocuenta_cuenta', to='codificadores.cuenta')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoflujocuenta_producto', to='codificadores.productoflujo')),
            ],
            options={
                'db_table': 'cla_productoflujocuenta',
            },
        ),
        migrations.CreateModel(
            name='ProductoFlujoDestino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destino', models.CharField(choices=[('C', 'Consumo Nacional'), ('E', 'Exportación')], max_length=1)),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoflujodestino_producto', to='codificadores.productoflujo')),
            ],
            options={
                'db_table': 'cla_productoflujodestino',
            },
        ),
        migrations.CreateModel(
            name='ProductoFlujoVitola',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoflujovitola_producto', to='codificadores.productoflujo')),
                ('idvitola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoflujovitola_vitola', to='codificadores.productoflujo')),
            ],
            options={
                'db_table': 'cla_productoflujovitola',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoCuenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idcuenta_debe_cn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipodocumentocuenta_cuenta_debe_cn', to='codificadores.cuenta')),
                ('idcuenta_debe_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipodocumentocuenta_cuenta_debe_exp', to='codificadores.cuenta')),
                ('idcuenta_haber_cn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipodocumentocuenta_cuenta_haber_cn', to='codificadores.cuenta')),
                ('idcuenta_haber_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipodocumentocuenta_cuenta_haber_exp', to='codificadores.cuenta')),
                ('iddocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codificadores.tipodocumento')),
            ],
            options={
                'db_table': 'cla_tipodocumentocuenta',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoCuentaTransfExterna',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iddepartamento', models.ForeignKey(db_comment='Dpto de la unidad contable para la que se va a configurar el documento', on_delete=django.db.models.deletion.PROTECT, related_name='tipodocumentocuentatransfexterna_departamento', to='codificadores.departamento')),
                ('iddocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codificadores.tipodocumento')),
                ('idunidadcontable', models.ForeignKey(db_comment='Esta es la unidad contable para la que se va a configurar el documento', on_delete=django.db.models.deletion.PROTECT, related_name='tipodocumentocuentatransfexterna_unidadcontable', to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'cla_tipodocumentocuentatransfexterna',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoProductoSalida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iddepartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentoproductosalida_departamento', to='codificadores.departamento')),
                ('idtipoproducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamentoproductosalida_producto', to='codificadores.tipoproducto')),
            ],
            options={
                'db_table': 'cla_departamentoproductosalida',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoCuentaTransfExternaUEB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idcuenta_debe_cn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipodocumentocuentatransfexternadpto_cuenta_debe_cn', to='codificadores.cuenta')),
                ('idcuenta_debe_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipodocumentocuentatransfexternadpto_cuenta_debe_exp', to='codificadores.cuenta')),
                ('idcuenta_haber_cn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipodocumentocuentatransfexternadpto_cuenta_haber_cn', to='codificadores.cuenta')),
                ('idcuenta_haber_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipodocumentocuentatransfexternadpto_cuenta_haber_exp', to='codificadores.cuenta')),
                ('idtipodocumentocuentatransfexterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipodocumentocuentatransfexternadpto_ipodocumentocuentatransfexterna', to='codificadores.tipodocumentocuentatransfexterna')),
                ('idunidadcontable', models.ForeignKey(db_comment='Unidad contab que recibe o envía la transf, según el tipo de documento', on_delete=django.db.models.deletion.PROTECT, related_name='tipodocumentocuentatransfexternadpto_unidadcontable', to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'cla_tipodocumentocuentatransfexternaueb',
            },
        ),
        migrations.CreateModel(
            name='Vitola',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diametro', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('longitud', models.IntegerField(default=0)),
                ('destino', models.CharField(choices=[('C', 'Consumo Nacional'), ('E', 'Exportación')], max_length=1)),
                ('cepo', models.IntegerField(default=0)),
                ('idcategoriavitola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vitola_categotia', to='codificadores.categoriavitola')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitola_producto', to='codificadores.productoflujo')),
                ('idtipovitola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vitola_tipo', to='codificadores.tipovitola')),
            ],
            options={
                'db_table': 'cla_vitola',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoRelacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iddepartamentod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentorelacion_destino', to='codificadores.departamento')),
                ('iddepartamentoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentorelacion_origen', to='codificadores.departamento')),
            ],
            options={
                'db_table': 'cla_departamentorelacion',
                'unique_together': {('iddepartamentoo', 'iddepartamentod')},
            },
        ),
        migrations.CreateModel(
            name='MedidaConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor_conversion', models.DecimalField(db_comment='Factor de conversión', decimal_places=6, max_digits=10)),
                ('medidad', models.ForeignKey(db_comment='Medida destino de la conversión', on_delete=django.db.models.deletion.CASCADE, related_name='medidaconversion_destino', to='codificadores.medida')),
                ('medidao', models.ForeignKey(db_comment='Medida origen de la conversión', on_delete=django.db.models.deletion.CASCADE, related_name='medidaconversion_origen', to='codificadores.medida')),
            ],
            options={
                'db_table': 'cla_medidaconversion',
                'ordering': ['medidao__descripcion'],
                'unique_together': {('medidao', 'medidad')},
            },
        ),
    ]
