# Generated by Django 5.0 on 2024-03-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcasalida',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='medida',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
