# Generated by Django 5.0 on 2023-12-12 22:36

from django.db import migrations, transaction
from codificadores.datos_iniciales import tipovitola, tipodocumento, motivoajuste, categoriavitola, \
    estadoproducto, clasemateriaprima, tipoproducto, numeraciondocumentos


def load_data(apps, schema_editor):
    """
    Args:
        apps:
        schema_editor:
    """
    with transaction.atomic():
        tipoproducto.init_data(apps, schema_editor)
        tipovitola.init_data(apps, schema_editor)
        tipodocumento.init_data(apps, schema_editor)
        motivoajuste.init_data(apps, schema_editor)
        categoriavitola.init_data(apps, schema_editor)
        estadoproducto.init_data(apps, schema_editor)
        clasemateriaprima.init_data(apps, schema_editor)
        numeraciondocumentos.init_data(apps, schema_editor)

class Migration(migrations.Migration):
    dependencies = [
        ('codificadores', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
