# Generated by Django 5.0 on 2024-04-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaconsumo',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Pesada'), (2, 'Materia Prima'), (4, 'Línea de Salida'), (5, 'Vitola'), (7, 'Habilitados')], verbose_name='Type'),
        ),
    ]
