# Generated by Django 5.0 on 2024-02-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrocosto',
            options={'ordering': ['descripcion', 'clave'], 'verbose_name': 'Cost center', 'verbose_name_plural': 'Centers of cost'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ['clave', 'posicion'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='medida',
            options={'ordering': ['clave', 'descripcion'], 'verbose_name': 'Unit of measurement', 'verbose_name_plural': 'Measurement units'},
        ),
        migrations.AlterModelOptions(
            name='medidaconversion',
            options={'ordering': ['medidao__descripcion'], 'verbose_name': 'Convert unit of measurement', 'verbose_name_plural': 'Convert measurement units'},
        ),
        migrations.AlterModelOptions(
            name='unidadcontable',
            options={'ordering': ['codigo'], 'verbose_name': 'UEB', 'verbose_name_plural': 'UEBs'},
        ),
        migrations.AddIndex(
            model_name='centrocosto',
            index=models.Index(fields=['clave'], name='cla_centroc_clave_7ed83d_idx'),
        ),
        migrations.AddIndex(
            model_name='cuenta',
            index=models.Index(fields=['clave'], name='cla_cuenta_clave_f63dff_idx'),
        ),
        migrations.AddIndex(
            model_name='medida',
            index=models.Index(fields=['clave', 'descripcion'], name='cla_medida_clave_ee8e43_idx'),
        ),
        migrations.AddIndex(
            model_name='medidaconversion',
            index=models.Index(fields=['medidao', 'medidad'], name='cla_medidac_medidao_706d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadcontable',
            index=models.Index(fields=['codigo'], name='cla_unidadc_codigo_ea13a8_idx'),
        ),
    ]
