# Generated by Django 5.0 on 2024-02-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ('codigo',)},
        ),
    ]
