# Generated by Django 5.0 on 2024-06-25 10:04

import codificadores.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0002_cargar_datos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='operacion',
            field=django_choices_field.fields.TextChoicesField(choices=[('E', 'Entrada'), ('S', 'Salida')], choices_enum=codificadores.models.OperacionDocumento, db_comment='Operación de Entrada (E) o Salida (S)', max_length=1, verbose_name='Operación'),
        ),
    ]
