# Generated by Django 5.0 on 2024-01-15 13:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0002_init_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=125, unique=True)),
                ('descripcion', models.CharField(max_length=125, unique=True)),
                ('inicializado', models.BooleanField(default=False)),
                ('idcentrocosto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamento2_centrocosto', to='codificadores.centrocosto')),
                ('idunidadcontable', models.ManyToManyField(related_name='departamento2_unidadcontable', to='codificadores.unidadcontable')),
            ],
        ),
    ]
