# Generated by Django 5.0 on 2024-02-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0002_alter_departamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='departamentoproducto',
            field=models.ManyToManyField(blank=True, null=True, related_name='departamentoproductosalida_producto', to='codificadores.tipoproducto', verbose_name='Output Product'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='id',
            field=models.AutoField(choices=[(1, 'Entrada Desde Versat'), (2, 'Salida Hacia Versat'), (3, 'Transferencia Hacia Departamento'), (4, 'Transferencia Desde Departamento'), (5, 'Ajuste de Aumento'), (6, 'Ajuste de Disminución'), (7, 'Recepción de Producción de Reproceso'), (8, 'Recepción de Producción'), (9, 'Devolución'), (10, 'Sobrante Sujeto a Investigación'), (11, 'Recepción de Rechazo'), (12, 'Carga Inicial'), (13, 'Devolución Recibida'), (14, 'Cambio de Estado'), (15, 'Transferencia Externa'), (16, 'Recibir Transferencia Externa'), (17, 'Venta a Trabajadores'), (18, 'Reporte de SubProductos'), (19, 'Cambio de Producto')], editable=False, primary_key=True, serialize=False),
        ),
    ]
