# Generated by Django 5.0 on 2024-02-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0002_alter_medida_options_alter_medidaconversion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrocosto',
            options={'ordering': ['descripcion', 'clave'], 'verbose_name': 'Cost center', 'verbose_name_plural': 'Centers of cost'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ['clave', 'posicion'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AddIndex(
            model_name='centrocosto',
            index=models.Index(fields=['clave'], name='cla_centroc_clave_7ed83d_idx'),
        ),
        migrations.AddIndex(
            model_name='cuenta',
            index=models.Index(fields=['clave'], name='cla_cuenta_clave_f63dff_idx'),
        ),
    ]
