# Generated by Django 5.0 on 2024-06-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0002_cargar_datos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichacostofilas',
            name='filasasumar',
            field=models.ManyToManyField(blank=True, db_comment='Filas encabezadas que se suman', null=True, related_name='sumafilasficha', to='codificadores.fichacostofilas', verbose_name='Filas a sumar'),
        ),
    ]
