# Generated by Django 5.0.7 on 2024-07-19 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0002_cargar_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionesGen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor')),
            ],
            options={
                'db_table': 'cla_configuracionesgen',
                'indexes': [models.Index(fields=['clave'], name='cla_configu_clave_5f1962_idx')],
            },
        ),
    ]
