# Generated by Django 5.0 on 2024-04-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0002_alter_normaconsumo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoflujo',
            name='descripcion',
            field=models.CharField(max_length=400, verbose_name='Description'),
        ),
    ]
