# Generated by Django 5.0 on 2024-03-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0002_marcasalida_activa_medida_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivoajuste',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
