# Generated by Django 5.0 on 2024-05-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0002_cargar_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='prefijo',
            field=models.CharField(blank=True, db_comment='Prefijo para el número de control', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='operacion',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], db_comment='Operación de Entrada (E) o Salida (S)', max_length=1),
        ),
    ]
