# Generated by Django 5.0 on 2024-05-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0003_tipodocumento_prefijo_alter_tipodocumento_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaconsumo',
            name='activa',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
