# Generated by Django 5.0 on 2024-01-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0003_departamento2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departamento2',
        ),
    ]
