# Generated by Django 5.0 on 2024-03-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0003_motivoajuste_activo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='centrocosto',
            name='cla_centroc_clave_7ed83d_idx',
        ),
        migrations.RemoveField(
            model_name='centrocosto',
            name='clavenivel',
        ),
        migrations.AddIndex(
            model_name='centrocosto',
            index=models.Index(fields=['clave', 'descripcion'], name='cla_centroc_clave_f9da43_idx'),
        ),
    ]
