# Generated by Django 5.0 on 2024-04-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0003_alter_productoflujo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='orden',
            field=models.SmallIntegerField(default=1),
        ),
    ]
