# Generated by Django 5.0.7 on 2024-07-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0003_configuracionesgen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionesgen',
            name='valor',
            field=models.BooleanField(default=True, verbose_name='Valor'),
        ),
    ]
