# Generated by Django 5.0 on 2024-03-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0004_remove_centrocosto_cla_centroc_clave_7ed83d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocosto',
            name='clave',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
    ]
