# Generated by Django 5.0 on 2024-04-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0004_tipoproducto_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoproducto',
            options={'ordering': ['orden', 'descripcion']},
        ),
    ]
