# Generated by Django 5.0.7 on 2024-07-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0004_alter_configuracionesgen_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionesgen',
            name='valor',
        ),
        migrations.AddField(
            model_name='configuracionesgen',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
