# Generated by Django 5.0 on 2024-06-15 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0004_fichacostofilas_padre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='inicializado',
        ),
        migrations.CreateModel(
            name='FechaInicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Date')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechainicio_departamento', to='codificadores.departamento', verbose_name='Department')),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechainicio_ueb', to='codificadores.unidadcontable', verbose_name='UEB')),
            ],
            options={
                'db_table': 'fp_fechainicio',
                'indexes': [models.Index(fields=['departamento', 'ueb'], name='fp_fechaini_departa_a72a07_idx')],
                'unique_together': {('departamento', 'ueb')},
            },
        ),
    ]
