# Generated by Django 5.0 on 2024-05-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0004_alter_normaconsumo_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaconsumo',
            name='confirmada',
            field=models.BooleanField(default=False, verbose_name='Confirmada'),
        ),
    ]
