# Generated by Django 5.0 on 2024-04-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0005_alter_centrocosto_clave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['codigo'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['codigo', 'descripcion', 'centrocosto'], name='cla_departa_codigo_9c90b9_idx'),
        ),
    ]
