# Generated by Django 5.0 on 2024-05-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0005_normaconsumo_confirmada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normaconsumo',
            options={'ordering': ['producto__tipoproducto', 'producto__descripcion']},
        ),
        migrations.AlterModelOptions(
            name='normaconsumogrouped',
            options={'ordering': ['producto__tipoproducto', 'producto__descripcion', 'fecha']},
        ),
        migrations.RemoveField(
            model_name='normaconsumo',
            name='tipo',
        ),
    ]
