# Generated by Django 5.0 on 2024-04-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0006_alter_lineasalida_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medida',
            name='clave',
            field=models.CharField(max_length=6, unique=True, verbose_name='U.M'),
        ),
    ]
