# Generated by Django 5.0 on 2024-05-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0006_alter_normaconsumo_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='normaconsumodetalle',
            unique_together={('normaconsumo', 'producto')},
        ),
    ]
