# Generated by Django 5.0 on 2024-04-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0006_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoflujo',
            name='clasemateriaprima',
            field=models.ManyToManyField(blank=True, null=True, to='codificadores.clasemateriaprima', verbose_name='Clase Materia Prima'),
        ),
    ]
