# Generated by Django 5.0 on 2024-04-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0007_alter_medida_clave'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaConsumoGrouped',
            fields=[
            ],
            options={
                'ordering': ['tipo', 'producto__descripcion', 'fecha'],
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('codificadores.normaconsumo',),
        ),
    ]
