# Generated by Django 5.0 on 2024-05-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0007_alter_normaconsumodetalle_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoFlujoVitola',
        ),
    ]
