# Generated by Django 5.0 on 2024-04-02 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0007_productoflujo_clasemateriaprima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoflujo',
            name='clasemateriaprima',
            field=models.ManyToManyField(blank=True, null=True, related_name='productoflujoclase_clasemateriaprima', to='codificadores.clasemateriaprima', verbose_name='Clase Materia Prima'),
        ),
        migrations.AlterField(
            model_name='productoflujoclase',
            name='clasemateriaprima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productosflujoclase_clasemateriaprima', to='codificadores.clasemateriaprima'),
        ),
    ]
