# Generated by Django 5.0 on 2024-05-24 15:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0008_delete_productoflujovitola'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEscalaCargo',
            fields=[
                ('id', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=10, unique=True)),
                ('salario', models.DecimalField(db_comment='Salario', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='The value must be greater than 0')], verbose_name='Salario')),
            ],
            options={
                'db_table': 'cla_grupoescalacargo',
            },
        ),
        migrations.AlterModelOptions(
            name='normaconsumo',
            options={'ordering': ['producto__tipoproducto', 'producto__descripcion', 'confirmada', '-activa']},
        ),
        migrations.CreateModel(
            name='FichaCostoFilas',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('fila', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('encabezado', models.BooleanField(default=False)),
                ('salario', models.BooleanField(default=False)),
                ('desglosado', models.BooleanField(default=False)),
                ('calculado', models.BooleanField(default=False)),
                ('sumafilas', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'cla_fichacostofilas',
                'ordering': ['fila'],
                'indexes': [models.Index(fields=['fila', 'descripcion'], name='cla_fichaco_fila_0edcf3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClasificadorCargos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=160, unique=True)),
                ('actividad', models.CharField(choices=[('C', 'Consumo Nacional'), ('E', 'Exportación')], max_length=1, verbose_name='Actividad')),
                ('directo', models.BooleanField(default=True, verbose_name='Directo')),
                ('indirecto_produccion', models.BooleanField(default=True, verbose_name='Indirecto Producción')),
                ('indirecto', models.BooleanField(default=True, verbose_name='Indirecto')),
                ('unidadcontable', models.ManyToManyField(related_name='cargo_unidadcontable', to='codificadores.unidadcontable', verbose_name='UEB')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_grupo', to='codificadores.grupoescalacargo', verbose_name='Grupo Escala')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListadoOficialPrecio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Precio')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lop_medida', to='codificadores.medida', verbose_name='U.M')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lop_producto', to='codificadores.productoflujo', unique=True, verbose_name='Product')),
            ],
            options={
                'db_table': 'cla_listadooficialprecio',
                'ordering': ['producto__tipoproducto', 'producto__descripcion'],
                'indexes': [models.Index(fields=['producto'], name='cla_listado_product_af1492_idx')],
            },
        ),
    ]
