# Generated by Django 5.0 on 2024-04-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0008_alter_productoflujo_clasemateriaprima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoflujo',
            name='clasemateriaprima',
        ),
    ]
