# Generated by Django 5.0 on 2024-05-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0009_grupoescalacargo_alter_normaconsumo_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clasificadorcargos',
            index=models.Index(fields=['codigo', 'descripcion', 'grupo', 'actividad'], name='cla_clasifi_codigo_17fab6_idx'),
        ),
        migrations.AlterModelTable(
            name='clasificadorcargos',
            table='cla_clasificadorcargos',
        ),
    ]
