# Generated by Django 5.0 on 2024-04-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0009_remove_productoflujo_clasemateriaprima'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cambioproducto',
            options={'ordering': ['productoo__descripcion'], 'verbose_name': 'Cambio de Producto', 'verbose_name_plural': 'Cambio de Productos'},
        ),
        migrations.AddIndex(
            model_name='cambioproducto',
            index=models.Index(fields=['productoo', 'productod'], name='cla_cambiop_product_fcf89d_idx'),
        ),
    ]
