# Generated by Django 5.0 on 2024-04-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0009_alter_normaconsumogrouped_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeraciondocumentos',
            name='prefijo',
            field=models.BooleanField(db_comment='Si el número de documento va a contener un prefijo', default=False, verbose_name='Prefix'),
        ),
    ]
