# Generated by Django 5.0 on 2024-05-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0010_clasificadorcargos_cla_clasifi_codigo_17fab6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificadorcargos',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='clasificadorcargos',
            name='directo',
            field=models.BooleanField(default=False, verbose_name='Directo'),
        ),
        migrations.AlterField(
            model_name='clasificadorcargos',
            name='indirecto',
            field=models.BooleanField(default=False, verbose_name='Indirecto'),
        ),
        migrations.AlterField(
            model_name='clasificadorcargos',
            name='indirecto_produccion',
            field=models.BooleanField(default=False, verbose_name='Indirecto Producción'),
        ),
    ]
