# Generated by Django 5.0 on 2024-04-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0010_alter_numeraciondocumentos_prefijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeraciondocumentos',
            name='tiponumeracion',
            field=models.IntegerField(choices=[(1, 'Número Consecutivo'), (2, 'Número de Control')], unique=True, verbose_name='Enumeration Type'),
        ),
    ]
