# Generated by Django 5.0 on 2024-05-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0011_clasificadorcargos_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoescalacargo',
            name='salario_decreto',
            field=models.DecimalField(db_comment='Salario', decimal_places=2, default=0.0, max_digits=10, verbose_name='Salario Decreto'),
        ),
    ]
