# Generated by Django 5.0 on 2024-04-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0012_confcentroselementosotros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCapasClaPesadas',
            fields=[
            ],
            options={
                'ordering': [['tipoproducto', 'descripcion']],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('codificadores.productoflujo',),
        ),
    ]
