# Generated by Django 5.0 on 2024-05-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0012_grupoescalacargo_salario_decreto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoescalacargo',
            name='salario_decreto',
        ),
    ]
