# Generated by Django 5.0 on 2024-05-03 17:06

from django.db import migrations
from codificadores.fixtures import F002_datos_iniciales_grupoescala


def load_data(apps, schema_editor):
    F002_datos_iniciales_grupoescala.init_data(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ('codificadores', '0013_remove_grupoescalacargo_salario_decreto'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
