# Generated by Django 5.0 on 2024-05-26 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0014_cargar_datos_grupo_salarial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='centrocosto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamento_centrocosto', to='codificadores.centrocosto', unique=True, verbose_name='Cost Center'),
        ),
    ]
