# Generated by Django 5.0 on 2024-05-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0015_alter_departamento_centrocosto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriavitola',
            name='capas',
            field=models.ManyToManyField(related_name='capas_categvitolas', to='codificadores.productoflujo', verbose_name='Capas sin clasificar'),
        ),
    ]
