# Generated by Django 5.0 on 2024-05-28 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0016_categoriavitola_capas'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoflujo',
            name='precio_lop',
            field=models.DecimalField(db_comment='Precio según Listado Oficial de Precio', decimal_places=4, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='El valor debe ser > 0')], verbose_name='Precio LOP'),
        ),
    ]
