# Generated by Django 5.0 on 2024-05-29 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0017_productoflujo_precio_lop'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoflujo',
            name='rendimientocapa',
            field=models.IntegerField(db_comment='Rendimiento de la capa x millar', default=0, validators=[django.core.validators.MinValueValidator(0, message='El valor debe ser >= 0')], verbose_name='Rendimiento x Millar'),
        ),
    ]
