# Generated by Django 5.0 on 2024-06-02 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0018_productoflujo_rendimientocapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificadorcargos',
            name='norma_tiempo',
            field=models.IntegerField(default=0, verbose_name='Norma de tiempo (hrs)'),
        ),
        migrations.AddField(
            model_name='clasificadorcargos',
            name='nr_media',
            field=models.IntegerField(db_comment='Norma de Rendimiento Media para los trabajadores directos', default=0, verbose_name='Norma Rendimiento Media'),
        ),
        migrations.AlterField(
            model_name='productoflujo',
            name='precio_lop',
            field=models.DecimalField(db_comment='Precio según Listado Oficial de Precio', decimal_places=4, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='El valor debe ser >= 0')], verbose_name='Precio LOP'),
        ),
    ]
