# Generated by Django 5.0 on 2024-06-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0019_clasificadorcargos_norma_tiempo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriavitola',
            name='capas',
        ),
    ]
