# Generated by Django 5.0 on 2024-06-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0020_remove_categoriavitola_capas'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoflujo',
            name='vitolas',
            field=models.ManyToManyField(related_name='capas_categvitolas', to='codificadores.categoriavitola', verbose_name='Vitolas'),
        ),
    ]
