# Generated by Django 5.0 on 2024-06-02 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0021_productoflujo_vitolas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificadorcargos',
            name='norma_tiempo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='El valor debe ser >= 0')], verbose_name='Norma de tiempo (hrs)'),
        ),
    ]
