# Generated by Django 5.0 on 2024-06-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0022_alter_clasificadorcargos_norma_tiempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasificadorcargos',
            name='directo',
        ),
        migrations.RemoveField(
            model_name='clasificadorcargos',
            name='indirecto',
        ),
        migrations.RemoveField(
            model_name='clasificadorcargos',
            name='indirecto_produccion',
        ),
        migrations.AddField(
            model_name='clasificadorcargos',
            name='vinculo_produccion',
            field=models.SmallIntegerField(choices=[(1, 'Directo'), (2, 'Indirecto Producción'), (3, 'Indirecto')], db_comment='Directo (1), Indirecto Producción (2), Indirecto (3)', default=1, verbose_name='Vinculo Producción'),
        ),
    ]
