# Generated by Django 5.0 on 2024-06-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0023_remove_clasificadorcargos_directo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadooficialprecio',
            name='medida',
        ),
        migrations.RemoveField(
            model_name='listadooficialprecio',
            name='producto',
        ),
        migrations.RemoveIndex(
            model_name='clasificadorcargos',
            name='cla_clasifi_codigo_17fab6_idx',
        ),
        migrations.AddIndex(
            model_name='clasificadorcargos',
            index=models.Index(fields=['codigo', 'descripcion', 'grupo', 'actividad', 'vinculo_produccion'], name='cla_clasifi_codigo_d6a4e1_idx'),
        ),
        migrations.DeleteModel(
            name='ListadoOficialPrecio',
        ),
    ]
