# Generated by Django 5.0 on 2024-06-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0024_remove_listadooficialprecio_medida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichacostofilas',
            name='vacaciones',
            field=models.BooleanField(db_comment='Si es vacaciones y se relaciona con el concepto salario para calcularlo como el 9.09 del salario', default=False),
        ),
        migrations.AlterField(
            model_name='fichacostofilas',
            name='calculado',
            field=models.BooleanField(db_comment='Si su valor depende de la suma de otras filas del encabezado', default=False),
        ),
        migrations.AlterField(
            model_name='fichacostofilas',
            name='desglosado',
            field=models.BooleanField(db_comment='Si el concepto es resultado de los desgloses establecidos salario, materia primas y materiales', default=False),
        ),
        migrations.AlterField(
            model_name='fichacostofilas',
            name='encabezado',
            field=models.BooleanField(db_comment='Valor True si tiene descendientes y su valor es la suma de los hijos los valores de sus hijos. Ejemplo Fila 1 es encabezado si exiten filas 1.1, 1.2, 1.n y el valor de Fila 1 es la suma de sus hijos', default=False),
        ),
        migrations.AlterField(
            model_name='fichacostofilas',
            name='salario',
            field=models.BooleanField(db_comment='Si el concepto constituye salario', default=False),
        ),
        migrations.AlterField(
            model_name='fichacostofilas',
            name='sumafilas',
            field=models.CharField(db_comment='Filas encabezadas que se suman', max_length=250),
        ),
    ]
