# Generated by Django 5.0 on 2024-06-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0025_fichacostofilas_vacaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichacostofilas',
            name='fila',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, unique=True),
        ),
    ]
