# Generated by Django 5.0 on 2024-06-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0026_alter_fichacostofilas_fila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichacostofilas',
            name='desglosado',
            field=models.BooleanField(db_comment='Si el concepto es resultado de los desgloses establecidos: Salario, Materia Prima y Materiales, Gastos Materia Prima Tabaco', default=False),
        ),
    ]
