# Generated by Django 5.0 on 2024-05-03 17:06

from django.db import migrations
from codificadores.fixtures import F003_datos_iniciales_filasfichacosto


def load_data(apps, schema_editor):
    F003_datos_iniciales_filasfichacosto.init_data(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ('codificadores', '0027_alter_fichacostofilas_desglosado'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
